name: CI
on:  [workflow_dispatch, pull_request, push]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: "full-stack-metaflow"
          python-version: "3.8"
          mamba-version: "*"
          channels: conda-forge
          environment-file: env.yml
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install git+https://github.com/fastai/nbprocess.git@master
      - name: Test Notebooks
        run: nbprocess_test
